# mahdidarabi/inotify-tools:1.0.0

# Build base image
ARG BUILD_IMG=debian:bookworm-20250113-slim

# Use a base image with inotify-tools
FROM ${BUILD_IMG}

# Install inotify-tools
RUN apt-get update && apt-get install -y inotify-tools && rm -rf /var/lib/apt/lists/*

CMD [ "inotifywait", "-h" ]